# Generated by Django 5.2.1 on 2026-06-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_confirm_password_alter_user_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="activity_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sedentary", "Sedentary"),
                    ("light", "Light"),
                    ("moderate", "Moderate"),
                    ("active", "Active"),
                    ("very active", "Very Active"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="current_weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="target_weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
