# Generated by Django 5.2.1 on 2026-07-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_userprofile_activity_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="goal",
            field=models.CharField(
                choices=[
                    ("lose weight", "Lose Weight"),
                    ("gain weight", "Gain Weight"),
                    ("maintain weight", "Maintain Weight"),
                    ("build muscle", "Build Muscle"),
                ],
                max_length=20,
            ),
        ),
    ]
