# Generated by Django 5.2.1 on 2026-05-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="meal_images/"),
        ),
    ]
