# Generated by Django 5.2.1 on 2026-07-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0003_mealplan_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="calories",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meal",
            name="category",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meal",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meal",
            name="id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="meal",
            name="image",
            field=models.ImageField(
                blank=True, max_length=2000, null=True, upload_to="meal_images/"
            ),
        ),
    ]
