# Generated by Django 5.2.1 on 2026-06-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0002_workoutplan_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workout",
            name="calories_burned",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="description",
        ),
        migrations.AddField(
            model_name="workout",
            name="api_source_id",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="workout",
            name="difficulty",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="workout",
            name="equipment",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="workout",
            name="instructions",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="workout",
            name="secondary_muscles",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="workout",
            name="target_muscle",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="workout",
            name="category",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="workout",
            name="duration",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workout",
            name="importance",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="workout",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
